"""
Sterilization process simulation → data/gold/experiment_1/process_1/datasets/

Produces:
  df_event_log.parquet       – process event log (same schema as process_2)
  df_expanded.parquet        – minute-resolution energy + weather time series
  df_production_plan.parquet – one row per batch

Autoclave heat/hold/cool power curves are generated by the physical model in
`autoclave_function.sterilization_profile` (not a synthetic formula) — one
profile per autoclave cycle, resampled to the discrete-event timestamps.

One plant-level coupling is deliberately built in, because it is what the
downstream models are supposed to discover (see the VOLUME block below):

  batch volume  -> case duration.  `volume_L` scales the duration of every
      station that handles the product volume, INCLUDING the autoclave cycle
      (a bigger load takes longer to come up to sterilization temperature).
      Previously the autoclave — the longest station — ignored volume, so
      volume explained only ~4% of total case duration and no case-duration
      model could beat a constant.

  batch volume  -> autoclave energy levels.  The steam mass flow the operator
      sets on the valve (`m_dot_steam`) and the cooling-water flow
      (`m_dot_cool`) both scale with the charge, so the heat-phase steam
      plateau (m_dot_steam * h_vap) and the cool-phase cooling-water peak are
      predominantly determined by `volume_L`, with only a few percent of
      residual noise on top. Previously both flows were drawn as pure +-18%
      per-cycle noise with no recorded cause, so the plateau of every
      `autoclaving_*_heat` instance varied for reasons no attribute-conditioned
      model could learn — the level models could only predict a constant.

The weather does NOT drive the energy demand of this process
(WEATHER_ENERGY_COUPLING = False): the distillation duty and the autoclave
losses are solved at a fixed ambient temperature (FIXED_AMBIENT_C, applied
through `physics_ambient_c`), so this process is the one where the exogenous
factors carry no signal. The `ef_*` columns are still written to the expanded
frame from the deterministic `weather_at` series as before, so the exogenous
features exist and the models can be run unchanged — they simply have nothing
to find here. Every other process keeps its weather coupling.

NOTE this paragraph described the intended behaviour before the switch existed:
until 2026-07-24 the code passed the real ambient temperature into both the
distillation duty scaling and the autoclave physics, so process_1 WAS weather-
coupled despite the docstring. Datasets generated before that date carry the
coupling and must be regenerated to match this description.
"""

import sys
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from functools import lru_cache
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from autoclave_function import sterilization_profile
from destilation_function import DistillationEnergyDemand

# ── Configuration ─────────────────────────────────────────────────────────────

N_BATCHES      = 300#300   # one batch every 4 h × 365 days = 1 year of production
START_DATE     = datetime(2024, 1, 15)
RANDOM_SEED    = 42
VOLUME_RANGE_L = (200, 800)   # uniform per batch
RECIPE_WEIGHTS = {'standard': 1.0}

# Process sequence (ordered)
PROCESS_SEQUENCE = [
    'Water_supply',
    'Destillation',
    'Bottling',
    'Autoclaving',
    'Individual_packaging',
    'Warehousing',
]

# Number of parallel resources per station
NUM_RESOURCES = {
    'Water_supply': 1,
    'Destillation': 1,
    'Bottling':     1,
    'Autoclaving':  3,
    'Individual_packaging':    1,
    'Warehousing':  1,
}

# Soft routing preference for Autoclaving resources: the slot is picked at random
# with probability proportional to AUTOCLAVE_RESOURCE_WEIGHT / wait_time, so
# autoclaving_2 gets more batches on average, but a resource that's genuinely much
# less busy right now still wins most of the time (wait_time dominates the score).
AUTOCLAVE_RESOURCE_WEIGHT = {0: 1.0, 1: 1.8, 2: 1.0}

# Internal activities per station + (base_duration_minutes, relative_variability) per recipe
# duration in minutes
PROCESS_CONFIG = {
    'Water_supply': {
        'volume_affected': True,
        'events': [
            {'name': 'prepare', 'recipes': {
                'standard': {'duration': 0.06,  'variability': 0.01},
                'cleaning': {'duration': 0.06,  'variability': 0.01}}},
            {'name': 'working', 'recipes': {
                'standard': {'duration': 1.2,   'variability': 0.01},
                'cleaning': {'duration': 1.2,   'variability': 0.01}}},
        ],
    },
    'Destillation': {
        'volume_affected': True,
        # 'maintenance' is not part of the regular sequence — it is inserted
        # rarely after 'emptying', the same way Autoclaving reworks are inserted
        # after 'cool' (see simulate()).
        'events': [
            {'name': 'preparation', 'recipes': {
                'standard': {'duration': 3.0,   'variability': 0.05},
                'cleaning': {'duration': 3.0,   'variability': 0.05}}},
            {'name': 'production',  'recipes': {
                'standard': {'duration': 25.0,  'variability': 0.05},
                'cleaning': {'duration': 25.0,  'variability': 0.05}}},
            {'name': 'emptying',    'recipes': {
                'standard': {'duration': 4.0,   'variability': 0.05},
                'cleaning': {'duration': 4.0,   'variability': 0.05}}},
            {'name': 'maintenance', 'recipes': {
                'standard': {'duration': 15.0,  'variability': 0.10},
                'cleaning': {'duration': 15.0,  'variability': 0.10}}},
        ],
    },
    'Bottling': {
        'volume_affected': True,
        'events': [
            {'name': 'prepare', 'recipes': {
                'standard': {'duration': 0.06,  'variability': 0.05},
                'cleaning': {'duration': 0.06,  'variability': 0.05}}},
            {'name': 'working', 'recipes': {
                'standard': {'duration': 0.67,  'variability': 0.05},
                'cleaning': {'duration': 0.67,  'variability': 0.05}}},
            {'name': 'cool',    'recipes': {
                'standard': {'duration': 0.06,  'variability': 0.05},
                'cleaning': {'duration': 0.06,  'variability': 0.05}}},
        ],
    },
    'Autoclaving': {
        'volume_affected': False,
        'events': [
            {'name': 'prepare', 'recipes': {
                'standard': {'duration': 2.0,   'variability': 0.02},
                'cleaning': {'duration': 0.0,   'variability': 0.02}}},
            {'name': 'heat',    'recipes': {
                'standard': {'duration': 18.0,  'variability': 0.02},
                'cleaning': {'duration': 10.0,  'variability': 0.02}}},
            {'name': 'hold',    'recipes': {
                'standard': {'duration': 14.0,  'variability': 0.02},
                'cleaning': {'duration': 7.0,   'variability': 0.02}}},
            {'name': 'cool',    'recipes': {
                'standard': {'duration': 28.0,  'variability': 0.02},
                'cleaning': {'duration': 15.0,  'variability': 0.02}}},
        ],
    },
    'Individual_packaging': {
        # Number of units to pack scales with the batch volume.
        'volume_affected': True,
        'events': [
            {'name': 'prepare', 'recipes': {
                'standard': {'duration': 5.0,   'variability': 0.05},
                'cleaning': {'duration': 0.001, 'variability': 0.05}}},
            {'name': 'working', 'recipes': {
                'standard': {'duration': 5.0,   'variability': 0.05},
                'cleaning': {'duration': 0.001, 'variability': 0.05}}},
        ],
    },
    'Warehousing': {
        'volume_affected': False,
        'events': [
            {'name': 'prepare', 'recipes': {
                'standard': {'duration': 5.0,   'variability': 0.05},
                'cleaning': {'duration': 0.001, 'variability': 0.05}}},
            {'name': 'working', 'recipes': {
                'standard': {'duration': 5.0,   'variability': 0.05},
                'cleaning': {'duration': 0.001, 'variability': 0.05}}},
        ],
    },
}

# Energy model parameters (base kW values and weather coefficients)
ENERGY_PARAMS = {
    'bottling':   {'base_kW': 35.0,  'noise_std': 2.0},
    'individual_packaging':  {'base_kW': 25.0,  'noise_std': 1.5},
}

# ── Standby (idle) draw per sensor, kW ───────────────────────────────────────
# Every minute belongs to exactly one station's activity, and previously the
# five *other* sensor columns were written as a hard 0.0. That made the sensors
# 52-98% exact zeros (bottling_power: 97.5%, only 900 non-zero samples in
# 36k rows), which is both unphysical and breaks the curve evaluation:
#   * relative metrics are undefined on an all-zero window (WAPE = 0/0 -> NaN,
#     silently dropped by the median), and
#   * absolute metrics are trivially perfect there (MAE = 0 exactly), which
#     dragged the median MAE for process_1 to 0.000 for most approaches.
# Real plant equipment never falls to 0 kW between batches — controls, PLCs,
# circulation pumps, chillers and insulation losses keep drawing. Each value
# below is ~3% of that sensor's typical operating level for the big thermal
# users and ~7% for the small electrical ones, with noise at ~8-12% of the
# standby level (so a negative draw is ~12 sigma away and never clips).
STANDBY_ENABLED = True   # False restores the old hard-zero behaviour
STANDBY_KW = {
    # column                                            (base_kW, noise_std)
    'destillation_steam_demand_kW_energy_to_model':      (45.0, 4.0),
    'destillation_cooling_demand_kW_energy_to_model':    (40.0, 3.5),
    # 85.0 was sized as ~3% of the HEAT phase (~3000 kW) — but the autoclave's
    # holding phase only draws A_U*(T_steri - T_amb) ~ 24 kW, i.e. well BELOW
    # that floor. `_floor` therefore overwrote every holding minute with the
    # standby draw, erasing the longest phase of the cycle (10.9k of 21.2k
    # autoclave rows) and with it the ambient-temperature coupling that phase
    # carries. Re-sized against the holding level instead: idle losses on a
    # vessel that is not at 121 degC are a fraction of the holding duty.
    'autoclave_steam_demand_kW_energy_to_model':         (6.0,  0.6),
    'autoclave_cooling_water_demand_kW_energy_to_model': (12.0, 1.2),
    'bottling_power_kW_energy_to_model':                 (2.5,  0.25),
    'individual_packaging_power_kW_energy_to_model':     (1.8,  0.18),
}


def _standby_levels(rng: np.random.Generator) -> dict[str, float]:
    """One noisy standby draw per sensor column, for a single minute."""
    if not STANDBY_ENABLED:
        return {col: 0.0 for col in STANDBY_KW}
    return {col: max(0.0, base + rng.normal(0, sd))
            for col, (base, sd) in STANDBY_KW.items()}

REFERENCE_VOLUME_L = 500.0  # volume scaling pivot

# Destillation energy demand comes from the physical model in
# `destilation_function.DistillationEnergyDemand` (steady-state heating_demand()
# / cooling_demand(), in kW), applied during 'production'. 'preparation' ramps
# up to 10% of the heating demand (steam only, no cooling). 'emptying' ramps
# the cooling demand down to 10% at the end (no steam). 'maintenance' is a
# rare, energy-free stop — see DESTILLATION_MAINTENANCE_PROB.
DISTILLATION_PROCESS_PARAMS = dict(
    mass_flow=12000 / 3600,   # kg/s
    fraction_lowbp=0.25,
    fraction_highbp=0.75,
    T_inlet=25,
    T_boil=137,
    h_vap=593,
    cp_distillate=2.52,
    cp_bottoms=2.38,
    T_outlet=30,
)
DESTILLATION_MAINTENANCE_PROB = 0.01   # same rate/pattern as the autoclave rework
DEMAND_NOISE_REL = 0.05                # +-5% noise on the destillation demand curves

# ── Ambient-temperature coupling of the distillation column ──────────────────
# The steady-state model is adiabatic, so on its own it returns the same kW for
# every batch all year. A real column standing in an unheated hall loses heat
# through its shell and reboiler, and its condenser rejects heat against
# ambient, so the duty moves with outside temperature: colder -> more steam to
# hold the boil-up, warmer -> more cooling to condense. Both effects are linear
# around DIST_TEMP_REF_C and sized well above DEMAND_NOISE_REL (+-5%) so the
# signal is recoverable rather than buried in measurement noise.
DIST_TEMP_REF_C       = 15.0
DIST_STEAM_TEMP_COEF  = 0.012   # +1.2% steam per degC BELOW the reference
DIST_COOL_TEMP_COEF   = 0.009   # +0.9% cooling per degC ABOVE the reference

# ── Weather → energy coupling (OFF for this process) ─────────────────────────
# When False, no energy quantity of process_1 depends on the weather: the
# distillation duty is evaluated at FIXED_AMBIENT_C instead of the ambient
# temperature of the batch, and the autoclave physics is solved at the same
# fixed ambient. The ef_* columns are still written to the expanded frame from
# the deterministic weather_at series, so the exogenous features exist and every
# model runs unchanged — they simply have nothing to find in this process.
# Set to True to restore the coupling (the header docstring described this
# switch before it existed; the code was still coupled).
WEATHER_ENERGY_COUPLING = False
FIXED_AMBIENT_C         = DIST_TEMP_REF_C   # ambient the physics is solved at


def physics_ambient_c(ts: datetime) -> float:
    """Ambient temperature the ENERGY physics is solved with for a timestamp.

    The real weather when the coupling is on, a constant when it is off. Kept
    separate from weather_at() on purpose: weather_at() keeps feeding the ef_*
    feature columns either way.
    """
    if not WEATHER_ENERGY_COUPLING:
        return FIXED_AMBIENT_C
    return weather_at(ts)[0]


def distillation_energy() -> tuple[float, float]:
    """Steady-state (heating_kW, cooling_kW) from the physical distillation model."""
    d = DistillationEnergyDemand(**DISTILLATION_PROCESS_PARAMS)
    return d.heating_demand(), d.cooling_demand()


def _distillation_curve(phase: str, n: int, rng: np.random.Generator,
                        T_amb_c: float) -> tuple[np.ndarray, np.ndarray]:
    """Per-minute (steam_kW, cooling_kW) for one Destillation phase at ambient T_amb_c."""
    heat_kw, cool_kw = distillation_energy()
    if WEATHER_ENERGY_COUPLING:
        heat_kw *= max(0.1, 1.0 + DIST_STEAM_TEMP_COEF * (DIST_TEMP_REF_C - T_amb_c))
        cool_kw *= max(0.1, 1.0 + DIST_COOL_TEMP_COEF * (T_amb_c - DIST_TEMP_REF_C))

    def noisy(base_arr: np.ndarray) -> np.ndarray:
        return np.clip(base_arr * (1.0 + rng.normal(0.0, DEMAND_NOISE_REL, len(base_arr))), 0, None)

    if phase == 'preparation':
        steam   = noisy(np.linspace(0.0, 0.10 * heat_kw, n))
        cooling = np.zeros(n)
    elif phase == 'production':
        steam   = noisy(np.full(n, heat_kw))
        cooling = noisy(np.full(n, cool_kw))
    elif phase == 'emptying':
        steam   = np.zeros(n)
        cooling = noisy(np.linspace(cool_kw, 0.10 * cool_kw, n))
    else:
        steam   = np.zeros(n)
        cooling = np.zeros(n)

    return steam, cooling

# Autoclave heat/hold/cool durations and power draw come from the physical
# model in `autoclave_function.sterilization_profile`, not a synthetic curve.
# `t_ges` (total heat+hold+cool duration, seconds) is sampled per cycle and
# the model's own fixed phase split (0.27 / 0.53 / 0.19) sets the durations
# of the 'heat', 'hold' and 'cool' events for that cycle.
AUTOCLAVE_CYCLE_BASE_MIN = {'standard': 60.0, 'cleaning': 32.0}
# Per-cycle duration noise, as a fraction of the volume-implied cycle length. This
# is the ONLY part of the duration no recorded attribute explains, so it caps how
# far volume_L can go: at 0.15 a regression of duration on volume_L lands at
# R^2 ~ 0.60-0.70 (residual sigma ~ 2.6 min on a 16 min heat phase), and the
# simulation's own duration model then predicts the conditional mean and loses
# that scatter entirely. Lowered so volume_L is the dominant driver; together
# with LOAD_FIXED_FRAC below this puts R^2 ~ 0.93.
AUTOCLAVE_CYCLE_VARIABILITY = 0.07

# Load coupling: the autoclave is the longest station in the line, and it used
# to be the ONLY one whose duration ignored volume_L. With a fixed steam supply
# a larger charge simply takes longer to reach sterilization temperature, so the
# cycle length is split into a load-independent part (vessel handling, valve
# sequencing, the sterilization hold itself) and a part proportional to the
# charge. This factor also enters m_cp, the thermal mass being heated (together
# with the charge factor below), which is what makes a big batch draw
# proportionally more cooling water on the way down.
AUTOCLAVE_LOAD_FIXED_FRAC = 0.20   # share of the cycle that does NOT scale with volume
                                   # (0.30 before: the smaller the fixed share, the wider
                                   # the volume-driven span of the cycle length. Second-order
                                   # next to CYCLE_VARIABILITY — 0.30 -> 0.20 is worth about
                                   # +0.05 R^2, the noise cut above about +0.21.)


def _load_factor(volume_L: float) -> float:
    """Duration/thermal-mass multiplier for a charge of `volume_L`."""
    return AUTOCLAVE_LOAD_FIXED_FRAC + (1.0 - AUTOCLAVE_LOAD_FIXED_FRAC) * (volume_L / REFERENCE_VOLUME_L)

# Steam / cooling-water FLOW SETTING as a function of the charge: the operator
# opens the steam valve further for a bigger batch, and the cooling circuit is
# run proportionally harder on the way down. This is what makes the energy
# LEVELS (heat-phase steam plateau = m_dot_steam * h_vap, cool-phase cooling
# peak) predictable from a recorded attribute instead of being nuisance noise.
# At VOLUME_RANGE_L = (200, 800) around REFERENCE_VOLUME_L = 500 the factor
# spans ~0.73 .. ~1.27, i.e. roughly the same visual spread the old +-18%
# per-cycle noise produced — but now caused by `volume_L`.
AUTOCLAVE_FLOW_FIXED_FRAC = 0.55   # share of the flow setting independent of the charge


def _flow_factor(volume_L: float) -> float:
    """Steam / cooling-water flow multiplier for a charge of `volume_L`."""
    return AUTOCLAVE_FLOW_FIXED_FRAC + (1.0 - AUTOCLAVE_FLOW_FIXED_FRAC) * (volume_L / REFERENCE_VOLUME_L)

# SCHEDULE coupling of the HOLDING phase. The holding duty is the vessel's heat
# loss, A_U*(T_steri - T_amb), and until now nothing in the log explained the
# batch-to-batch differences in it: the only thing that moved was the per-cycle
# A_U draw, a physical constant no event attribute records, so every
# attribute-conditioned model could do nothing but predict the leaf mean.
#
# It is now a function of WHEN the batch was scheduled on that autoclave: a vessel
# that starts a cycle straight after the previous one is still hot and loses less
# to the surroundings, one that has stood idle overnight starts cold and pays the
# full loss. The gap comes out of the schedule alone — no weather, no new physics —
# and it is written to the event's object_attributes as `idle_min`, so the feature
# frame the curve models build actually contains it.
#
# Sized against the idle gaps this schedule produces (11% of cycles back-to-back
# reworks, median gap ~7 h): WARM_FRAC 0.35 with TAU 480 min puts the duty factor
# at p10..p90 = 0.65..0.98 with a 12.9% CV, against the ~7.5% CV the A_U/T_steri
# draws contribute. Volume explains ~0.96 of the heat level; the schedule now
# explains ~0.75 of the hold level, the rest staying genuine nuisance noise.
AUTOCLAVE_HOLD_WARM_FRAC    = 0.35    # duty reduction for a vessel that is still fully warm
AUTOCLAVE_HOLD_WARM_TAU_MIN = 480.0   # idle minutes for the residual heat to decay by 1/e
# (no cold sentinel: a vessel with no previous cycle uses the visit-level idle gap,
# which is measured from the start of the simulation and is already "cold".)


def _hold_duty_factor(idle_min: float) -> float:
    """Holding-duty multiplier for a vessel idle `idle_min` minutes before this cycle."""
    return 1.0 - AUTOCLAVE_HOLD_WARM_FRAC * float(np.exp(-max(0.0, idle_min)
                                                         / AUTOCLAVE_HOLD_WARM_TAU_MIN))

# Physical parameters of `sterilization_profile` are also randomized per cycle
# (not just its duration), but only as a small residual on top of the
# attribute-driven levels above: the batch-to-batch differences in curve shape
# must be EXPLAINED by something the event log records, otherwise no
# attribute-conditioned level model can reproduce them. The per-cycle draws
# below are therefore the unexplained remainder only — a few percent — while
# the systematic spread comes from volume_L via `_flow_factor` / `_load_factor`
# (and, for the holding phase, from the ambient temperature through A_U).
AUTOCLAVE_PARAM_DEFAULTS = {
    'm_dot_steam': 1.94,
    'm_dot_cool':  14.00,
    'A_U':         0.20797,
    'T_steri':     394.25,
    'T_final':     333.15,
    'm_cp':        63032.0,
}
AUTOCLAVE_PARAM_VARIABILITY = {
    # Residual only — the systematic part of these two comes from _flow_factor.
    'm_dot_steam': 0.04,
    'm_dot_cool':  0.04,
    # A_U sets the holding-phase steam draw via Q = A_U*(T_steri - T_amb). At the
    # old +-18% this per-cycle nuisance spread was larger than the ~+-17% swing
    # the ambient temperature itself produces over the year, i.e. it masked the
    # very weather coupling the exogenous-factor models are meant to find.
    # Tightened so ambient temperature is the dominant driver of hold steam.
    'A_U':         0.06,
    'T_steri':     0.01,   # sterilization target: only a few K of spread
    'T_final':     0.02,
    'm_cp':        0.05,
}


def generate_autoclave_cycle(rng: np.random.Generator, recipe: str, T_amb_c: float,
                             volume_L: float,
                             idle_min: float = 10_000.0) -> pd.DataFrame:   # default: cold vessel
    """One heat/hold/cool profile (time, temp, type, Q) from the physical autoclave model."""
    load = _load_factor(volume_L)
    flow = _flow_factor(volume_L)
    base_min = AUTOCLAVE_CYCLE_BASE_MIN[recipe] * load
    # Truncated at +-3 sd. An untruncated normal occasionally returns a cycle far
    # shorter than the charge allows (a -4.4 sd draw gave a 780 L batch a 28.6 min
    # cycle against a 83.6 min nominal); since the cool-phase peak is the cooling
    # energy divided by the cool-phase duration, such a draw produces a 4x power
    # spike that is neither physical nor explainable from the batch attributes.
    sd = base_min * AUTOCLAVE_CYCLE_VARIABILITY
    t_ges_min = max(5.0, float(np.clip(rng.normal(base_min, sd),
                                       base_min - 3.0 * sd, base_min + 3.0 * sd)))
    t_ges_s = int(round(t_ges_min * 60))

    params = {
        name: max(1e-4, rng.normal(default, default * AUTOCLAVE_PARAM_VARIABILITY[name]))
        for name, default in AUTOCLAVE_PARAM_DEFAULTS.items()
    }
    # Attribute-driven levels: the valve settings follow the charge size, so the
    # heat plateau and the cooling peak are functions of volume_L plus the small
    # residual already contained in the draws above.
    params['m_dot_steam'] *= flow
    params['m_dot_cool']  *= flow
    # Vessel + charge thermal mass. `load` is the duration-side coupling; `flow` is
    # the charge-size coupling of the levels. m_cp needs both: the cool-phase peak
    # is the cooling energy (proportional to m_cp) spread over the cool-phase
    # duration (also proportional to load), so a m_cp that only tracks `load`
    # largely cancels itself out and the peak barely moves with the charge.
    params['m_cp'] *= load * flow
    params['T_final'] = min(params['T_final'], params['T_steri'] - 20.0)  # stay physically valid

    return sterilization_profile(
        t_ges=t_ges_s,
        T_amb=T_amb_c + 273.15,
        hold_duty_factor=_hold_duty_factor(idle_min),   # schedule -> holding duty
        m_dot_steam=params['m_dot_steam'],
        m_dot_cool=params['m_dot_cool'],
        A_U=params['A_U'],
        T_steri=params['T_steri'],
        T_final=params['T_final'],
        m_cp=params['m_cp'],
        visual=False,
    )


# ── Helpers ───────────────────────────────────────────────────────────────────

def sample_duration(base_min: float, variability: float, volume_L: float,
                    volume_affected: bool, rng: np.random.Generator) -> float:
    """Sample duration in minutes, optionally scaled by volume."""
    if base_min <= 0:
        return 0.0
    std = base_min * variability
    dur = max(0.1, rng.normal(base_min, std))
    if volume_affected:
        dur *= volume_L / REFERENCE_VOLUME_L
    return dur


# ── Weather (external factor) ────────────────────────────────────────────────
# Weather is a DETERMINISTIC function of the timestamp: seasonal + diurnal
# harmonics plus a day-to-day anomaly drawn from a fixed seed and interpolated
# smoothly between midnights.
#
# It used to take an RNG and add white noise per call. That had two fatal
# consequences for anything trying to LEARN the weather coupling:
#   * the ambient temperature the autoclave physics was solved with (drawn in
#     simulate() from one stream) and the value written to
#     ef_temperature_2m_energy (drawn in build_expanded() from a different
#     stream) were two different numbers for the same instant — the recorded
#     external factor was not the one that actually drove the steam demand; and
#   * being redrawn per minute, the recorded series was white noise rather than
#     a weather signal, so its case-level mean carried almost no information.
# Now the same timestamp always yields the same reading, everywhere.
WEATHER_ANOMALY_SEED   = 20240115
WEATHER_T_ANOMALY_SD_C = 3.0    # day-to-day departure from the seasonal mean
WEATHER_RH_ANOMALY_SD  = 4.0


@lru_cache(maxsize=None)
def _daily_anomaly(day_index: int, which: str) -> float:
    """Fixed-seed daily weather anomaly, stable across processes and runs."""
    offset = 0 if which == 'T' else 100_000
    rng = np.random.default_rng(WEATHER_ANOMALY_SEED + offset + day_index)
    sd = WEATHER_T_ANOMALY_SD_C if which == 'T' else WEATHER_RH_ANOMALY_SD
    return float(rng.normal(0.0, sd))


def _interp_anomaly(ts: datetime, which: str) -> float:
    """Today's and tomorrow's anomaly, blended by time of day → continuous."""
    day_index = (ts.date() - START_DATE.date()).days
    f = (ts.hour * 60 + ts.minute) / 1440.0
    return ((1.0 - f) * _daily_anomaly(day_index, which)
            + f * _daily_anomaly(day_index + 1, which))


def weather_at(ts: datetime) -> tuple[float, float]:
    """Return (temperature_C, humidity_pct) for a given timestamp. Deterministic."""
    day_of_year = ts.timetuple().tm_yday
    # Seasonal sine: peaks in summer (~day 196)
    T = 15.0 + 13.0 * np.sin(2 * np.pi * (day_of_year - 80) / 365)
    T += 5.0 * np.sin(2 * np.pi * ts.hour / 24)   # diurnal variation
    T += _interp_anomaly(ts, 'T')
    RH = 75.0 - 0.8 * (T - 15.0) + _interp_anomaly(ts, 'RH')
    RH = float(np.clip(RH, 20.0, 100.0))
    return float(T), RH


# ── Simulation ────────────────────────────────────────────────────────────────

def simulate(n_batches: int = N_BATCHES,
             start_date: datetime = START_DATE,
             random_seed: int = RANDOM_SEED):
    rng = np.random.default_rng(random_seed)

    recipes = list(RECIPE_WEIGHTS.keys())
    recipe_probs = np.array(list(RECIPE_WEIGHTS.values()))
    recipe_probs /= recipe_probs.sum()

    # Resource availability: next free time for each resource slot
    resource_free: dict[str, list[datetime]] = {
        station: [start_date] * n_res
        for station, n_res in NUM_RESOURCES.items()
    }

    events: list[dict] = []
    autoclave_profiles: dict[str, pd.DataFrame] = {}
    cycle_counter = 0
    # When each autoclave last finished a cycle — the schedule quantity the holding
    # duty keys off. Missing = never used yet, i.e. a cold vessel.
    autoclave_last_end: dict[str, datetime] = {}

    for b in range(n_batches):
        case_id   = f'batch_{b+1:03d}'
        recipe    = rng.choice(recipes, p=recipe_probs)
        volume_L  = float(rng.uniform(*VOLUME_RANGE_L))
        obj_attrs = {'recipe': str(recipe), 'volume_L': round(float(volume_L), 1)}

        # Batch clock: when the batch is ready to enter the next station
        batch_ready = start_date + timedelta(minutes=b * 240)  # 4-h stagger → ~1 year for 2190 batches

        stations_queue = list(PROCESS_SEQUENCE)
        
        # Dynamic Skipping: 20% chance to skip Individual_packaging and go straight to Warehousing
        if rng.random() < 0.20:
            stations_queue = [s for s in stations_queue if s != 'Individual_packaging']

        while stations_queue:
            station = stations_queue.pop(0)

            cfg         = PROCESS_CONFIG[station]
            vol_affected = cfg['volume_affected']
            n_res        = NUM_RESOURCES[station]
            res_times    = resource_free[station]

            # Assign to the resource that becomes free soonest (Autoclaving instead
            # does a weighted random pick, favoring autoclaving_2 but still strongly
            # preferring whichever slot is genuinely less busy right now)
            if station == 'Autoclaving':
                wait_s = np.maximum(
                    np.array([t.timestamp() for t in res_times]) - batch_ready.timestamp(), 0.0
                ) + 60.0   # +1 min epsilon so a zero wait doesn't blow up the score
                pref = np.array([AUTOCLAVE_RESOURCE_WEIGHT.get(i, 1.0) for i in range(n_res)])
                probs = (pref / wait_s) / (pref / wait_s).sum()
                best_slot = int(rng.choice(n_res, p=probs))
            else:
                best_slot = int(np.argmin([t.timestamp() for t in res_times]))
            slot_free = res_times[best_slot]
            station_start = max(batch_ready, slot_free)
            # Idle gap of the chosen resource before this visit. Defined for EVERY
            # station, not just the autoclave: the attribute has to exist on every
            # event or the parquet round-trip fills it with None on the others, and a
            # NaN column reaches the regressors that cannot take one.
            station_idle_min = max(0.0, (station_start - slot_free).total_seconds() / 60.0)

            # Resource name
            if n_res == 1:
                resource_name = station.lower()
            else:
                resource_name = f'{station.lower()}_{best_slot + 1}'

            object_type = 'sterilization_line'

            current_time = station_start

            if station == 'Destillation':
                # 'maintenance' is inserted rarely, not run every visit (see below).
                events_to_process = [e for e in cfg['events'] if e['name'] != 'maintenance']
            else:
                events_to_process = list(cfg['events'])
            idx = 0
            current_cycle_id = None
            current_profile = None
            cycle_idle_min = station_idle_min

            while idx < len(events_to_process):
                event_def = events_to_process[idx]
                act_name = event_def['name']

                if station == 'Autoclaving' and act_name == 'prepare':
                    # How long this vessel stood idle before the cycle starts. Straight
                    # out of the schedule: 0 when the next batch was queued behind this
                    # one (or on a rework), hours when the autoclave waited for work.
                    # A rework restarts at 'prepare' seconds after 'cool', so measure
                    # from this vessel's own last cycle end rather than from the visit
                    # start. No previous cycle -> the visit's gap, i.e. idle since the
                    # simulation began, which is a cold vessel either way.
                    _last_end = autoclave_last_end.get(resource_name)
                    cycle_idle_min = (station_idle_min if _last_end is None else
                                      max(0.0, (current_time - _last_end).total_seconds() / 60.0))

                if station == 'Autoclaving' and act_name == 'heat':
                    # Start of a new sterilization cycle: draw a fresh physical profile.
                    cycle_counter += 1
                    current_cycle_id = f'ac_{cycle_counter}'
                    T_amb_c = physics_ambient_c(current_time)
                    current_profile = generate_autoclave_cycle(rng, recipe, T_amb_c, volume_L,
                                                               cycle_idle_min)
                    autoclave_profiles[current_cycle_id] = current_profile

                if station == 'Autoclaving' and act_name in ('heat', 'hold', 'cool') and current_profile is not None:
                    dur = (current_profile['type'] == act_name).sum() / 60.0  # seconds -> minutes
                    cycle_id = current_cycle_id
                else:
                    rec_cfg = event_def['recipes'][recipe]
                    dur = sample_duration(
                        rec_cfg['duration'], rec_cfg['variability'],
                        volume_L, vol_affected, rng
                    )
                    cycle_id = None

                # Machine Breakdowns removed as requested

                ts_start = current_time
                ts_end   = current_time + timedelta(minutes=dur)

                # Autoclave events also carry the vessel's idle gap, so the driver of
                # the holding level is IN THE LOG rather than hidden in the physics.
                _idle = (cycle_idle_min
                         if station == 'Autoclaving' and act_name in ('prepare', 'heat', 'hold', 'cool')
                         else station_idle_min)
                ev_attrs = {**obj_attrs, 'idle_min': round(float(_idle), 1)}

                events.append({
                    'case_id':               case_id,
                    'activity':              f'{resource_name}_{act_name}',
                    'timestamp_start':       ts_start,
                    'timestamp_end':         ts_end,
                    'higher_level_activity': 'sterilization_process',
                    'station':               station,
                    'object_type':           object_type,
                    'object':                resource_name,
                    'object_attributes':     ev_attrs,
                    'autoclave_cycle_id':    cycle_id,
                })
                current_time = ts_end + timedelta(seconds=1)

                # Cycle finished: this vessel starts cooling down from now on.
                if station == 'Autoclaving' and act_name == 'cool':
                    autoclave_last_end[resource_name] = ts_end
                
                # Microscopic rework inside Autoclave: the charge failed the cycle
                # and is sterilized again. A repeat ALWAYS restarts at 'prepare' —
                # the vessel has been cooled down and depressurized by 'cool', so it
                # has to be closed and brought back up before steam can be admitted.
                # A 'cool' -> 'heat' transition is physically impossible and must not
                # appear in the log; every cycle in the machine view is therefore a
                # complete prepare -> heat -> hold -> cool sequence.
                if station == 'Autoclaving' and act_name == 'cool':
                    if rng.random() < 0.15:  # 15% chance to rework
                        rework_events = [e for e in cfg['events']
                                         if e['name'] in ('prepare', 'heat', 'hold', 'cool')]
                        events_to_process = events_to_process[:idx+1] + rework_events + events_to_process[idx+1:]

                # Rare maintenance stop after Destillation emptying (same pattern as the autoclave rework)
                if station == 'Destillation' and act_name == 'emptying':
                    if rng.random() < DESTILLATION_MAINTENANCE_PROB:
                        maintenance_event = [e for e in cfg['events'] if e['name'] == 'maintenance']
                        events_to_process = events_to_process[:idx+1] + maintenance_event + events_to_process[idx+1:]

                idx += 1

            # Update resource and batch clocks
            res_times[best_slot] = current_time
            batch_ready          = current_time
            
            # Macroscopic rework: Warehousing -> Packaging
            if station == 'Warehousing':
                if rng.random() < 0.40: # 10% chance to fail QA and go back to Packaging
                    stations_queue.append('Individual_packaging')
                    stations_queue.append('Warehousing')

    df_event_log = pd.DataFrame(events)
    df_event_log['timestamp_start'] = pd.to_datetime(df_event_log['timestamp_start'])
    df_event_log['timestamp_end']   = pd.to_datetime(df_event_log['timestamp_end'])
    df_event_log = df_event_log.sort_values('timestamp_start').reset_index(drop=True)
    return df_event_log, autoclave_profiles


# ── Energy time series ────────────────────────────────────────────────────────

def _power_curve(activity: str, station: str, duration_min: float,
                 T: float, RH: float, rng: np.random.Generator) -> np.ndarray:
    """
    Return a 1-D array of power values (kW), one per minute of the activity.
    Returns None if this station/activity combination has no sensor.
    """
    n = max(1, int(round(duration_min)))
    t = np.linspace(0, 1, n)

    def noisy(base, noise_std):
        return base + rng.normal(0, noise_std, n)

    # Destillation preparation/production/emptying are driven by the physical
    # model (destilation_function.DistillationEnergyDemand) instead — see
    # _distillation_curve. 'maintenance' has no sensor (falls through to None).

    if station == 'Autoclaving':
        # heat/hold/cool are driven by the physical model (autoclave_function
        # .sterilization_profile) instead — see _autoclave_curve_from_profile.
        if activity == 'prepare':
            return noisy(5.0, 1.0)   # idle / loading power

    if station == 'Bottling':
        if activity == 'working':
            p = ENERGY_PARAMS['bottling']
            return noisy(p['base_kW'], p['noise_std'])
        if activity in ('prepare', 'cool'):
            return noisy(5.0, 0.5)

    if station == 'Individual_packaging' and activity == 'working':
        p = ENERGY_PARAMS['individual_packaging']
        return noisy(p['base_kW'], p['noise_std'])
    if station == 'Individual_packaging' and activity == 'prepare':
        return noisy(3.0, 0.3)

    return None   # no sensor for this combination (e.g. Water_supply, Warehousing)


def _resample_to_n(values: np.ndarray, n: int) -> np.ndarray:
    """Average per-second `values` into n equal-ish per-minute bins."""
    return np.array([chunk.mean() for chunk in np.array_split(values, n)])


def _autoclave_curve_from_profile(profile: pd.DataFrame | None, act_short: str,
                                  n_target: int) -> np.ndarray | None:
    """Per-minute steam/cooling power (kW) for one autoclave phase, from the physical model."""
    if profile is None:
        return None
    seg = profile.loc[profile['type'] == act_short, 'Q'].to_numpy()
    if len(seg) == 0:
        return None
    n = max(1, min(n_target, len(seg)))
    return _resample_to_n(seg, n)


def build_expanded(df_event_log: pd.DataFrame,
                   autoclave_profiles: dict[str, pd.DataFrame],
                   random_seed: int = RANDOM_SEED) -> pd.DataFrame:
    rng = np.random.default_rng(random_seed + 1)
    # Standby noise draws from its OWN stream. Sharing `rng` would consume draws
    # inside the per-minute loop and shift every subsequent weather / power-curve
    # sample, so switching STANDBY_ENABLED would silently re-roll the whole
    # dataset instead of only adding the idle floor.
    sb_rng = np.random.default_rng(random_seed + 2)

    rows: list[dict] = []

    for _, ev in df_event_log.iterrows():
        station   = ev['station']
        activity  = ev['activity']                          # compound: 'resource_actname'
        act_short = activity[len(ev['object']) + 1:]        # short:    'actname'
        ts_start = pd.Timestamp(ev['timestamp_start'])
        ts_end   = pd.Timestamp(ev['timestamp_end'])
        dur_min  = max(1.0, (ts_end - ts_start).total_seconds() / 60.0)

        # Weather of this instance: written to the ef_* feature columns below.
        # The ENERGY physics does not use it while WEATHER_ENERGY_COUPLING is
        # off — the distillation curve is evaluated at physics_ambient_c() and
        # _power_curve ignores T/RH entirely.
        T, RH = weather_at(ts_start.to_pydatetime())
        T_phys = physics_ambient_c(ts_start.to_pydatetime())

        dual_curve = None   # second sensor column (cooling), when a phase has both
        if station == 'Autoclaving' and act_short in ('heat', 'hold', 'cool') and ev['autoclave_cycle_id']:
            profile = autoclave_profiles.get(ev['autoclave_cycle_id'])
            curve = _autoclave_curve_from_profile(profile, act_short, max(1, int(round(dur_min))))
        elif station == 'Destillation' and act_short in ('preparation', 'production', 'emptying'):
            curve, dual_curve = _distillation_curve(act_short, max(1, int(round(dur_min))), rng, T_phys)
        else:
            curve = _power_curve(act_short, station, dur_min, T, RH, rng)
        if curve is None:
            continue

        n = len(curve)
        timestamps = pd.date_range(ts_start, periods=n, freq='min')

        for i, ts in enumerate(timestamps):
            T_i, RH_i = weather_at(ts.to_pydatetime())

            row: dict = {
                'datetime_energy':              ts,
                'ef_temperature_2m_energy':     T_i,
                'ef_relative_humidity_2m_energy': RH_i,
                # Every sensor starts at its standby draw; the station that is
                # actually running overwrites its own column below (see
                # STANDBY_KW for why this is not a hard 0.0).
                **_standby_levels(sb_rng),
                # Log columns
                'timestamp_start_log':          ev['timestamp_start'],
                'timestamp_end_log':            ev['timestamp_end'],
                'activity_log':                 ev['activity'],
                'higher_level_activity_log':    ev['higher_level_activity'],
                'station_log':                  ev['station'],
                'object_type_log':              ev['object_type'],
                'object_log':                   ev['object'],
                'case_id_log':                  ev['case_id'],
                'object_attributes_log':        ev['object_attributes'],
            }

            # Fill the correct sensor column. The reading is floored at this
            # minute's standby draw: a station that is running can still have a
            # phase where its process demand is 0 (distillation 'emptying'
            # closes the steam valve, 'preparation' has no cooling), but the
            # equipment is powered up, so the meter cannot read below standby.
            # Without this floor those phases put exact zeros back into the
            # active sensor -- ~4% of destillation_steam rows.
            def _floor(col, v):
                return max(row[col], max(0.0, float(v)))

            val = curve[i]
            if station == 'Destillation':
                row['destillation_steam_demand_kW_energy_to_model'] = \
                    _floor('destillation_steam_demand_kW_energy_to_model', val)
                if dual_curve is not None:
                    row['destillation_cooling_demand_kW_energy_to_model'] = \
                        _floor('destillation_cooling_demand_kW_energy_to_model', dual_curve[i])
            elif station == 'Autoclaving' and act_short in ('heat', 'hold', 'prepare'):
                row['autoclave_steam_demand_kW_energy_to_model'] = \
                    _floor('autoclave_steam_demand_kW_energy_to_model', val)
            elif station == 'Autoclaving' and act_short == 'cool':
                row['autoclave_cooling_water_demand_kW_energy_to_model'] = \
                    _floor('autoclave_cooling_water_demand_kW_energy_to_model', val)
            elif station == 'Bottling':
                row['bottling_power_kW_energy_to_model'] = \
                    _floor('bottling_power_kW_energy_to_model', val)
            elif station == 'Individual_packaging':
                row['individual_packaging_power_kW_energy_to_model'] = \
                    _floor('individual_packaging_power_kW_energy_to_model', val)

            rows.append(row)

    df = pd.DataFrame(rows)
    df['datetime_energy'] = pd.to_datetime(df['datetime_energy'])
    df['timestamp_start_log'] = pd.to_datetime(df['timestamp_start_log'])
    df['timestamp_end_log']   = pd.to_datetime(df['timestamp_end_log'])
    return df.sort_values('datetime_energy').reset_index(drop=True)


def build_production_plan(df_event_log: pd.DataFrame) -> pd.DataFrame:
    """One row per batch = first event for that case_id."""
    idx = df_event_log.groupby('case_id')['timestamp_start'].idxmin()
    pp  = df_event_log.loc[idx].reset_index(drop=True)
    return pp[['case_id', 'activity', 'timestamp_start', 'timestamp_end',
               'object_attributes']].copy()


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    # <repo_root>/data/gold/experiment_1/process_1/datasets — the same location used
    # by the original (non-physical) simulation, so this replaces it in place.
    out_dir = (
        Path(__file__).resolve().parent.parent.parent
        / 'data' / 'gold' / 'experiment_1' / 'process_1' / 'datasets'
    )
    out_dir.mkdir(parents=True, exist_ok=True)

    print("Simulating event log…")
    df_event_log, autoclave_profiles = simulate()
    print(f"  {len(df_event_log)} events, "
          f"{df_event_log['case_id'].nunique()} batches, "
          f"{df_event_log['station'].nunique()} stations, "
          f"{df_event_log['activity'].nunique()} unique activities, "
          f"{len(autoclave_profiles)} autoclave cycles")

    print("Building energy time series…")
    df_expanded = build_expanded(df_event_log, autoclave_profiles)
    print(f"  {len(df_expanded)} minute-resolution rows")

    print("Building production plan…")
    df_production_plan = build_production_plan(df_event_log)
    print(f"  {len(df_production_plan)} rows")

    df_event_log.to_parquet(out_dir / 'df_event_log.parquet', index=False)
    df_expanded.to_parquet(out_dir / 'df_expanded.parquet', index=False)
    df_production_plan.to_parquet(out_dir / 'df_production_plan.parquet', index=False)
    print(f"\nSaved to {out_dir}")


if __name__ == '__main__':
    main()
