"""
Sterilization process simulation → data/gold/experiment_1/process_1/datasets/

Produces:
  df_event_log.parquet       – process event log (same schema as process_2)
  df_expanded.parquet        – minute-resolution energy + weather time series
  df_production_plan.parquet – one row per batch

Autoclave heat/hold/cool power curves are generated by the physical model in
`autoclave_function.sterilization_profile` (not a synthetic formula) — one
profile per autoclave cycle, resampled to the discrete-event timestamps.
"""

import sys
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from autoclave_function import sterilization_profile
from destilation_function import DistillationEnergyDemand

# ── Configuration ─────────────────────────────────────────────────────────────

N_BATCHES      = 2190   # one batch every 4 h × 365 days = 1 year of production
START_DATE     = datetime(2024, 1, 15)
RANDOM_SEED    = 42
VOLUME_RANGE_L = (200, 800)   # uniform per batch
RECIPE_WEIGHTS = {'standard': 1.0}

# Process sequence (ordered)
PROCESS_SEQUENCE = [
    'Water_supply',
    'Destillation',
    'Bottling',
    'Autoclaving',
    'Individual_packaging',
    'Warehousing',
]

# Number of parallel resources per station
NUM_RESOURCES = {
    'Water_supply': 1,
    'Destillation': 1,
    'Bottling':     1,
    'Autoclaving':  3,
    'Individual_packaging':    1,
    'Warehousing':  1,
}

# Soft routing preference for Autoclaving resources: the slot is picked at random
# with probability proportional to AUTOCLAVE_RESOURCE_WEIGHT / wait_time, so
# autoclaving_2 gets more batches on average, but a resource that's genuinely much
# less busy right now still wins most of the time (wait_time dominates the score).
AUTOCLAVE_RESOURCE_WEIGHT = {0: 1.0, 1: 1.8, 2: 1.0}

# Internal activities per station + (base_duration_minutes, relative_variability) per recipe
# duration in minutes
PROCESS_CONFIG = {
    'Water_supply': {
        'volume_affected': True,
        'events': [
            {'name': 'prepare', 'recipes': {
                'standard': {'duration': 0.06,  'variability': 0.01},
                'cleaning': {'duration': 0.06,  'variability': 0.01}}},
            {'name': 'working', 'recipes': {
                'standard': {'duration': 1.2,   'variability': 0.01},
                'cleaning': {'duration': 1.2,   'variability': 0.01}}},
        ],
    },
    'Destillation': {
        'volume_affected': True,
        # 'maintenance' is not part of the regular sequence — it is inserted
        # rarely after 'emptying', the same way Autoclaving reworks are inserted
        # after 'cool' (see simulate()).
        'events': [
            {'name': 'preparation', 'recipes': {
                'standard': {'duration': 3.0,   'variability': 0.05},
                'cleaning': {'duration': 3.0,   'variability': 0.05}}},
            {'name': 'production',  'recipes': {
                'standard': {'duration': 25.0,  'variability': 0.05},
                'cleaning': {'duration': 25.0,  'variability': 0.05}}},
            {'name': 'emptying',    'recipes': {
                'standard': {'duration': 4.0,   'variability': 0.05},
                'cleaning': {'duration': 4.0,   'variability': 0.05}}},
            {'name': 'maintenance', 'recipes': {
                'standard': {'duration': 15.0,  'variability': 0.10},
                'cleaning': {'duration': 15.0,  'variability': 0.10}}},
        ],
    },
    'Bottling': {
        'volume_affected': True,
        'events': [
            {'name': 'prepare', 'recipes': {
                'standard': {'duration': 0.06,  'variability': 0.05},
                'cleaning': {'duration': 0.06,  'variability': 0.05}}},
            {'name': 'working', 'recipes': {
                'standard': {'duration': 0.67,  'variability': 0.05},
                'cleaning': {'duration': 0.67,  'variability': 0.05}}},
            {'name': 'cool',    'recipes': {
                'standard': {'duration': 0.06,  'variability': 0.05},
                'cleaning': {'duration': 0.06,  'variability': 0.05}}},
        ],
    },
    'Autoclaving': {
        'volume_affected': False,
        'events': [
            {'name': 'prepare', 'recipes': {
                'standard': {'duration': 2.0,   'variability': 0.02},
                'cleaning': {'duration': 0.0,   'variability': 0.02}}},
            {'name': 'heat',    'recipes': {
                'standard': {'duration': 18.0,  'variability': 0.02},
                'cleaning': {'duration': 10.0,  'variability': 0.02}}},
            {'name': 'hold',    'recipes': {
                'standard': {'duration': 14.0,  'variability': 0.02},
                'cleaning': {'duration': 7.0,   'variability': 0.02}}},
            {'name': 'cool',    'recipes': {
                'standard': {'duration': 28.0,  'variability': 0.02},
                'cleaning': {'duration': 15.0,  'variability': 0.02}}},
        ],
    },
    'Individual_packaging': {
        'volume_affected': False,
        'events': [
            {'name': 'prepare', 'recipes': {
                'standard': {'duration': 5.0,   'variability': 0.05},
                'cleaning': {'duration': 0.001, 'variability': 0.05}}},
            {'name': 'working', 'recipes': {
                'standard': {'duration': 5.0,   'variability': 0.05},
                'cleaning': {'duration': 0.001, 'variability': 0.05}}},
        ],
    },
    'Warehousing': {
        'volume_affected': False,
        'events': [
            {'name': 'prepare', 'recipes': {
                'standard': {'duration': 5.0,   'variability': 0.05},
                'cleaning': {'duration': 0.001, 'variability': 0.05}}},
            {'name': 'working', 'recipes': {
                'standard': {'duration': 5.0,   'variability': 0.05},
                'cleaning': {'duration': 0.001, 'variability': 0.05}}},
        ],
    },
}

# Energy model parameters (base kW values and weather coefficients)
ENERGY_PARAMS = {
    'bottling':   {'base_kW': 35.0,  'noise_std': 2.0},
    'individual_packaging':  {'base_kW': 25.0,  'noise_std': 1.5},
    'water_supply': {'base_kW': 8.0, 'noise_std': 0.5},
}

REFERENCE_VOLUME_L = 500.0  # volume scaling pivot

# Destillation energy demand comes from the physical model in
# `destilation_function.DistillationEnergyDemand` (steady-state heating_demand()
# / cooling_demand(), in kW), applied during 'production'. 'preparation' ramps
# up to 10% of the heating demand (steam only, no cooling). 'emptying' ramps
# the cooling demand down to 10% at the end (no steam). 'maintenance' is a
# rare, energy-free stop — see DESTILLATION_MAINTENANCE_PROB.
DISTILLATION_PROCESS_PARAMS = dict(
    mass_flow=12000 / 3600,   # kg/s
    fraction_lowbp=0.25,
    fraction_highbp=0.75,
    T_inlet=25,
    T_boil=137,
    h_vap=593,
    cp_distillate=2.52,
    cp_bottoms=2.38,
    T_outlet=30,
)
DESTILLATION_MAINTENANCE_PROB = 0.01   # same rate/pattern as the autoclave rework
DEMAND_NOISE_REL = 0.05                # +-5% noise on the destillation demand curves


def distillation_energy() -> tuple[float, float]:
    """Steady-state (heating_kW, cooling_kW) from the physical distillation model."""
    d = DistillationEnergyDemand(**DISTILLATION_PROCESS_PARAMS)
    return d.heating_demand(), d.cooling_demand()


def _distillation_curve(phase: str, n: int, rng: np.random.Generator) -> tuple[np.ndarray, np.ndarray]:
    """Per-minute (steam_kW, cooling_kW) for one Destillation phase."""
    heat_kw, cool_kw = distillation_energy()

    def noisy(base_arr: np.ndarray) -> np.ndarray:
        return np.clip(base_arr * (1.0 + rng.normal(0.0, DEMAND_NOISE_REL, len(base_arr))), 0, None)

    if phase == 'preparation':
        steam   = noisy(np.linspace(0.0, 0.10 * heat_kw, n))
        cooling = np.zeros(n)
    elif phase == 'production':
        steam   = noisy(np.full(n, heat_kw))
        cooling = noisy(np.full(n, cool_kw))
    elif phase == 'emptying':
        steam   = np.zeros(n)
        cooling = noisy(np.linspace(cool_kw, 0.10 * cool_kw, n))
    else:
        steam   = np.zeros(n)
        cooling = np.zeros(n)

    return steam, cooling

# Autoclave heat/hold/cool durations and power draw come from the physical
# model in `autoclave_function.sterilization_profile`, not a synthetic curve.
# `t_ges` (total heat+hold+cool duration, seconds) is sampled per cycle and
# the model's own fixed phase split (0.27 / 0.53 / 0.19) sets the durations
# of the 'heat', 'hold' and 'cool' events for that cycle.
AUTOCLAVE_CYCLE_BASE_MIN = {'standard': 60.0, 'cleaning': 32.0}
AUTOCLAVE_CYCLE_VARIABILITY = 0.15

# Physical parameters of `sterilization_profile` are also randomized per cycle
# (not just its duration) so batches produce visibly different curve shapes —
# different steam/cooling flow levels, plateau heights, wall-loss rates, etc.
# — instead of one shape merely stretched/compressed in time.
AUTOCLAVE_PARAM_DEFAULTS = {
    'm_dot_steam': 1.94,
    'm_dot_cool':  14.00,
    'A_U':         0.20797,
    'T_steri':     394.25,
    'T_final':     333.15,
    'm_cp':        63032.0,
}
AUTOCLAVE_PARAM_VARIABILITY = {
    'm_dot_steam': 0.18,
    'm_dot_cool':  0.18,
    'A_U':         0.18,
    'T_steri':     0.01,   # sterilization target: only a few K of spread
    'T_final':     0.02,
    'm_cp':        0.12,
}


def generate_autoclave_cycle(rng: np.random.Generator, recipe: str, T_amb_c: float) -> pd.DataFrame:
    """One heat/hold/cool profile (time, temp, type, Q) from the physical autoclave model."""
    base_min = AUTOCLAVE_CYCLE_BASE_MIN[recipe]
    t_ges_min = max(5.0, rng.normal(base_min, base_min * AUTOCLAVE_CYCLE_VARIABILITY))
    t_ges_s = int(round(t_ges_min * 60))

    params = {
        name: max(1e-4, rng.normal(default, default * AUTOCLAVE_PARAM_VARIABILITY[name]))
        for name, default in AUTOCLAVE_PARAM_DEFAULTS.items()
    }
    params['T_final'] = min(params['T_final'], params['T_steri'] - 20.0)  # stay physically valid

    return sterilization_profile(
        t_ges=t_ges_s,
        T_amb=T_amb_c + 273.15,
        m_dot_steam=params['m_dot_steam'],
        m_dot_cool=params['m_dot_cool'],
        A_U=params['A_U'],
        T_steri=params['T_steri'],
        T_final=params['T_final'],
        m_cp=params['m_cp'],
        visual=False,
    )


# ── Helpers ───────────────────────────────────────────────────────────────────

def sample_duration(base_min: float, variability: float, volume_L: float,
                    volume_affected: bool, rng: np.random.Generator) -> float:
    """Sample duration in minutes, optionally scaled by volume."""
    if base_min <= 0:
        return 0.0
    std = base_min * variability
    dur = max(0.1, rng.normal(base_min, std))
    if volume_affected:
        dur *= volume_L / REFERENCE_VOLUME_L
    return dur


def weather_at(ts: datetime, rng: np.random.Generator) -> tuple[float, float]:
    """Return (temperature_C, humidity_pct) for a given timestamp."""
    day_of_year = ts.timetuple().tm_yday
    # Seasonal sine: peaks in summer (~day 196)
    T = 15.0 + 13.0 * np.sin(2 * np.pi * (day_of_year - 80) / 365)
    T += 5.0 * np.sin(2 * np.pi * ts.hour / 24)   # diurnal variation
    T += rng.normal(0, 1.5)
    RH = 75.0 - 0.8 * (T - 15.0) + rng.normal(0, 5.0)
    RH = float(np.clip(RH, 20.0, 100.0))
    return float(T), RH


# ── Simulation ────────────────────────────────────────────────────────────────

def simulate(n_batches: int = N_BATCHES,
             start_date: datetime = START_DATE,
             random_seed: int = RANDOM_SEED):
    rng = np.random.default_rng(random_seed)

    recipes = list(RECIPE_WEIGHTS.keys())
    recipe_probs = np.array(list(RECIPE_WEIGHTS.values()))
    recipe_probs /= recipe_probs.sum()

    # Resource availability: next free time for each resource slot
    resource_free: dict[str, list[datetime]] = {
        station: [start_date] * n_res
        for station, n_res in NUM_RESOURCES.items()
    }

    events: list[dict] = []
    autoclave_profiles: dict[str, pd.DataFrame] = {}
    cycle_counter = 0

    for b in range(n_batches):
        case_id   = f'batch_{b+1:03d}'
        recipe    = rng.choice(recipes, p=recipe_probs)
        volume_L  = float(rng.uniform(*VOLUME_RANGE_L))
        obj_attrs = {'recipe': str(recipe), 'volume_L': round(float(volume_L), 1)}

        # Batch clock: when the batch is ready to enter the next station
        batch_ready = start_date + timedelta(minutes=b * 240)  # 4-h stagger → ~1 year for 2190 batches

        stations_queue = list(PROCESS_SEQUENCE)
        
        # Dynamic Skipping: 20% chance to skip Individual_packaging and go straight to Warehousing
        if rng.random() < 0.20:
            stations_queue = [s for s in stations_queue if s != 'Individual_packaging']

        while stations_queue:
            station = stations_queue.pop(0)

            cfg         = PROCESS_CONFIG[station]
            vol_affected = cfg['volume_affected']
            n_res        = NUM_RESOURCES[station]
            res_times    = resource_free[station]

            # Assign to the resource that becomes free soonest (Autoclaving instead
            # does a weighted random pick, favoring autoclaving_2 but still strongly
            # preferring whichever slot is genuinely less busy right now)
            if station == 'Autoclaving':
                wait_s = np.maximum(
                    np.array([t.timestamp() for t in res_times]) - batch_ready.timestamp(), 0.0
                ) + 60.0   # +1 min epsilon so a zero wait doesn't blow up the score
                pref = np.array([AUTOCLAVE_RESOURCE_WEIGHT.get(i, 1.0) for i in range(n_res)])
                probs = (pref / wait_s) / (pref / wait_s).sum()
                best_slot = int(rng.choice(n_res, p=probs))
            else:
                best_slot = int(np.argmin([t.timestamp() for t in res_times]))
            slot_free = res_times[best_slot]
            station_start = max(batch_ready, slot_free)

            # Resource name
            if n_res == 1:
                resource_name = station.lower()
            else:
                resource_name = f'{station.lower()}_{best_slot + 1}'

            object_type = 'sterilization_line'

            current_time = station_start

            if station == 'Destillation':
                # 'maintenance' is inserted rarely, not run every visit (see below).
                events_to_process = [e for e in cfg['events'] if e['name'] != 'maintenance']
            else:
                events_to_process = list(cfg['events'])
            idx = 0
            current_cycle_id = None
            current_profile = None

            while idx < len(events_to_process):
                event_def = events_to_process[idx]
                act_name = event_def['name']

                if station == 'Autoclaving' and act_name == 'heat':
                    # Start of a new sterilization cycle: draw a fresh physical profile.
                    cycle_counter += 1
                    current_cycle_id = f'ac_{cycle_counter}'
                    T_amb_c, _ = weather_at(current_time, rng)
                    current_profile = generate_autoclave_cycle(rng, recipe, T_amb_c)
                    autoclave_profiles[current_cycle_id] = current_profile

                if station == 'Autoclaving' and act_name in ('heat', 'hold', 'cool') and current_profile is not None:
                    dur = (current_profile['type'] == act_name).sum() / 60.0  # seconds -> minutes
                    cycle_id = current_cycle_id
                else:
                    rec_cfg = event_def['recipes'][recipe]
                    dur = sample_duration(
                        rec_cfg['duration'], rec_cfg['variability'],
                        volume_L, vol_affected, rng
                    )
                    cycle_id = None

                # Machine Breakdowns removed as requested

                ts_start = current_time
                ts_end   = current_time + timedelta(minutes=dur)

                events.append({
                    'case_id':               case_id,
                    'activity':              f'{resource_name}_{act_name}',
                    'timestamp_start':       ts_start,
                    'timestamp_end':         ts_end,
                    'higher_level_activity': 'sterilization_process',
                    'station':               station,
                    'object_type':           object_type,
                    'object':                resource_name,
                    'object_attributes':     obj_attrs,
                    'autoclave_cycle_id':    cycle_id,
                })
                current_time = ts_end + timedelta(seconds=1)
                
                # Microscopic rework inside Autoclave
                if station == 'Autoclaving' and act_name == 'cool':
                    if rng.random() < 0.15:  # 15% chance to rework
                        if rng.random() < 0.5:  # 50% of reworks start from heat
                            rework_events = [e for e in cfg['events'] if e['name'] in ('heat', 'hold', 'cool')]
                        else:                   # 50% of reworks start from prepare
                            rework_events = [e for e in cfg['events'] if e['name'] in ('prepare', 'heat', 'hold', 'cool')]
                        events_to_process = events_to_process[:idx+1] + rework_events + events_to_process[idx+1:]

                # Rare maintenance stop after Destillation emptying (same pattern as the autoclave rework)
                if station == 'Destillation' and act_name == 'emptying':
                    if rng.random() < DESTILLATION_MAINTENANCE_PROB:
                        maintenance_event = [e for e in cfg['events'] if e['name'] == 'maintenance']
                        events_to_process = events_to_process[:idx+1] + maintenance_event + events_to_process[idx+1:]

                idx += 1

            # Update resource and batch clocks
            res_times[best_slot] = current_time
            batch_ready          = current_time
            
            # Macroscopic rework: Warehousing -> Packaging
            if station == 'Warehousing':
                if rng.random() < 0.40: # 10% chance to fail QA and go back to Packaging
                    stations_queue.append('Individual_packaging')
                    stations_queue.append('Warehousing')

    df_event_log = pd.DataFrame(events)
    df_event_log['timestamp_start'] = pd.to_datetime(df_event_log['timestamp_start'])
    df_event_log['timestamp_end']   = pd.to_datetime(df_event_log['timestamp_end'])
    df_event_log = df_event_log.sort_values('timestamp_start').reset_index(drop=True)
    return df_event_log, autoclave_profiles


# ── Energy time series ────────────────────────────────────────────────────────

def _power_curve(activity: str, station: str, duration_min: float,
                 T: float, RH: float, rng: np.random.Generator) -> np.ndarray:
    """
    Return a 1-D array of power values (kW), one per minute of the activity.
    Returns None if this station/activity combination has no sensor.
    """
    n = max(1, int(round(duration_min)))
    t = np.linspace(0, 1, n)

    def noisy(base, noise_std):
        return base + rng.normal(0, noise_std, n)

    # Destillation preparation/production/emptying are driven by the physical
    # model (destilation_function.DistillationEnergyDemand) instead — see
    # _distillation_curve. 'maintenance' has no sensor (falls through to None).

    if station == 'Autoclaving':
        # heat/hold/cool are driven by the physical model (autoclave_function
        # .sterilization_profile) instead — see _autoclave_curve_from_profile.
        if activity == 'prepare':
            return noisy(5.0, 1.0)   # idle / loading power

    if station == 'Bottling':
        if activity == 'working':
            p = ENERGY_PARAMS['bottling']
            return noisy(p['base_kW'], p['noise_std'])
        if activity in ('prepare', 'cool'):
            return noisy(5.0, 0.5)

    if station == 'Individual_packaging' and activity == 'working':
        p = ENERGY_PARAMS['individual_packaging']
        return noisy(p['base_kW'], p['noise_std'])
    if station == 'Individual_packaging' and activity == 'prepare':
        return noisy(3.0, 0.3)

    if station == 'Water_supply' and activity == 'working':
        p = ENERGY_PARAMS['water_supply']
        return noisy(p['base_kW'], p['noise_std'])
    if station == 'Water_supply' and activity == 'prepare':
        return noisy(1.0, 0.2)

    return None   # no sensor for this combination


def _resample_to_n(values: np.ndarray, n: int) -> np.ndarray:
    """Average per-second `values` into n equal-ish per-minute bins."""
    return np.array([chunk.mean() for chunk in np.array_split(values, n)])


def _autoclave_curve_from_profile(profile: pd.DataFrame | None, act_short: str,
                                  n_target: int) -> np.ndarray | None:
    """Per-minute steam/cooling power (kW) for one autoclave phase, from the physical model."""
    if profile is None:
        return None
    seg = profile.loc[profile['type'] == act_short, 'Q'].to_numpy()
    if len(seg) == 0:
        return None
    n = max(1, min(n_target, len(seg)))
    return _resample_to_n(seg, n)


def build_expanded(df_event_log: pd.DataFrame,
                   autoclave_profiles: dict[str, pd.DataFrame],
                   random_seed: int = RANDOM_SEED) -> pd.DataFrame:
    rng = np.random.default_rng(random_seed + 1)

    rows: list[dict] = []

    for _, ev in df_event_log.iterrows():
        station   = ev['station']
        activity  = ev['activity']                          # compound: 'resource_actname'
        act_short = activity[len(ev['object']) + 1:]        # short:    'actname'
        ts_start = pd.Timestamp(ev['timestamp_start'])
        ts_end   = pd.Timestamp(ev['timestamp_end'])
        dur_min  = max(1.0, (ts_end - ts_start).total_seconds() / 60.0)

        T, RH = weather_at(ts_start.to_pydatetime(), rng)

        dual_curve = None   # second sensor column (cooling), when a phase has both
        if station == 'Autoclaving' and act_short in ('heat', 'hold', 'cool') and ev['autoclave_cycle_id']:
            profile = autoclave_profiles.get(ev['autoclave_cycle_id'])
            curve = _autoclave_curve_from_profile(profile, act_short, max(1, int(round(dur_min))))
        elif station == 'Destillation' and act_short in ('preparation', 'production', 'emptying'):
            curve, dual_curve = _distillation_curve(act_short, max(1, int(round(dur_min))), rng)
        else:
            curve = _power_curve(act_short, station, dur_min, T, RH, rng)
        if curve is None:
            continue

        n = len(curve)
        timestamps = pd.date_range(ts_start, periods=n, freq='min')

        for i, ts in enumerate(timestamps):
            T_i, RH_i = weather_at(ts.to_pydatetime(), rng)

            row: dict = {
                'datetime_energy':              ts,
                'ef_temperature_2m_energy':     T_i,
                'ef_relative_humidity_2m_energy': RH_i,
                # All sensors default to 0 (only the active one is filled)
                'destillation_steam_demand_kW_energy_to_model':          0.0,
                'destillation_cooling_demand_kW_energy_to_model':        0.0,
                'autoclave_steam_demand_kW_energy_to_model':             0.0,
                'autoclave_cooling_water_demand_kW_energy_to_model':     0.0,
                'bottling_power_kW_energy_to_model':                     0.0,
                'individual_packaging_power_kW_energy_to_model':                    0.0,
                'water_supply_power_kW_energy_to_model':                 0.0,
                # Log columns
                'timestamp_start_log':          ev['timestamp_start'],
                'timestamp_end_log':            ev['timestamp_end'],
                'activity_log':                 ev['activity'],
                'higher_level_activity_log':    ev['higher_level_activity'],
                'station_log':                  ev['station'],
                'object_type_log':              ev['object_type'],
                'object_log':                   ev['object'],
                'case_id_log':                  ev['case_id'],
                'object_attributes_log':        ev['object_attributes'],
            }

            # Fill the correct sensor column
            val = max(0.0, float(curve[i]))
            if station == 'Destillation':
                row['destillation_steam_demand_kW_energy_to_model'] = val
                if dual_curve is not None:
                    row['destillation_cooling_demand_kW_energy_to_model'] = max(0.0, float(dual_curve[i]))
            elif station == 'Autoclaving' and act_short in ('heat', 'hold', 'prepare'):
                row['autoclave_steam_demand_kW_energy_to_model'] = val
            elif station == 'Autoclaving' and act_short == 'cool':
                row['autoclave_cooling_water_demand_kW_energy_to_model'] = val
            elif station == 'Bottling':
                row['bottling_power_kW_energy_to_model'] = val
            elif station == 'Individual_packaging':
                row['individual_packaging_power_kW_energy_to_model'] = val
            elif station == 'Water_supply':
                row['water_supply_power_kW_energy_to_model'] = val

            rows.append(row)

    df = pd.DataFrame(rows)
    df['datetime_energy'] = pd.to_datetime(df['datetime_energy'])
    df['timestamp_start_log'] = pd.to_datetime(df['timestamp_start_log'])
    df['timestamp_end_log']   = pd.to_datetime(df['timestamp_end_log'])
    return df.sort_values('datetime_energy').reset_index(drop=True)


def build_production_plan(df_event_log: pd.DataFrame) -> pd.DataFrame:
    """One row per batch = first event for that case_id."""
    idx = df_event_log.groupby('case_id')['timestamp_start'].idxmin()
    pp  = df_event_log.loc[idx].reset_index(drop=True)
    return pp[['case_id', 'activity', 'timestamp_start', 'timestamp_end',
               'object_attributes']].copy()


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    # <repo_root>/data/gold/experiment_1/process_1/datasets — the same location used
    # by the original (non-physical) simulation, so this replaces it in place.
    out_dir = (
        Path(__file__).resolve().parent.parent.parent
        / 'data' / 'gold' / 'experiment_1' / 'process_1' / 'datasets'
    )
    out_dir.mkdir(parents=True, exist_ok=True)

    print("Simulating event log…")
    df_event_log, autoclave_profiles = simulate()
    print(f"  {len(df_event_log)} events, "
          f"{df_event_log['case_id'].nunique()} batches, "
          f"{df_event_log['station'].nunique()} stations, "
          f"{df_event_log['activity'].nunique()} unique activities, "
          f"{len(autoclave_profiles)} autoclave cycles")

    print("Building energy time series…")
    df_expanded = build_expanded(df_event_log, autoclave_profiles)
    print(f"  {len(df_expanded)} minute-resolution rows")

    print("Building production plan…")
    df_production_plan = build_production_plan(df_event_log)
    print(f"  {len(df_production_plan)} rows")

    df_event_log.to_parquet(out_dir / 'df_event_log.parquet', index=False)
    df_expanded.to_parquet(out_dir / 'df_expanded.parquet', index=False)
    df_production_plan.to_parquet(out_dir / 'df_production_plan.parquet', index=False)
    print(f"\nSaved to {out_dir}")


if __name__ == '__main__':
    main()
